= atest(1)

== NAME
atest - run atests


== SYNOPSIS
*atest* ['FILE']..


== DESCRIPTION
atest(1) runs atests

== TUTORIAL

Lets create a test for a program `atest.example.sh`

....
$ ./atest.example.sh
....

it outputs

....
	 1 2 3 4 5
....

and you want to modify `atest.example.sh` and make sure the output is
the same after modifications.

Create a file with a test `test/0`

....
	# cTEST: 0
	./atest.example.sh  > example.out.txt
....

It is a shell script with a special pattern in a first line.  A file
name example.out.txt contains a "magic" pattern *.out.* which tells
atest to consider this as a reference output. Run

....
$ atest test/0
....

end of the output says:

....
	atest: 0/0 test(s) passed
	atest:    1 test(s) created
....

atest created directory test_data and stored output in it.

To run a test. Replace `cTEST` by ``TEST` in `test/0` and run
....
$ atest test/0
....

It returns

....
	atest: RUNNING: 0
	atest: PASSED : 0
	atest: 1/1 test(s) passed
....

Now if you "break" `atest.example.sh` and run `atest test/0` it get
noticed.

....
    atest: 0/1 test(s) passed
    atest: failed tests:
    atest:     0
....

== EXAMPLES
`atest atest.examples.sh`
