'\" t
.\"     Title: atest
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/13/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ATEST" "1" "06/13/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
atest \- run atests
.SH "SYNOPSIS"
.sp
\fBatest\fR [\fIFILE\fR]\&.\&.
.SH "TUTORIAL"
.sp
Lets create a test for a program atest\&.example\&.sh
.sp
.if n \{\
.RS 4
.\}
.nf
$ \&./example
.fi
.if n \{\
.RE
.\}
.sp
it outputs \fB1 2 3\fR and you want to modify \fI\&./example\fR and make sure the output stay the same\&.
.sp
Create a file with a test \fItest/0\fR
.sp
.if n \{\
.RS 4
.\}
.nf
# cTEST: 0
\&./example  > example\&.out\&.txt
.fi
.if n \{\
.RE
.\}
.sp
The lines after \fI# cTEST: 0\fR are executed as a script\&. The script creates a file example\&.out\&.txt which contains a "magic" pattern \fI\&.out\&.\fR\&. This pattern tells atest to consider this file as a reference output\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ atest test/0
.fi
.if n \{\
.RE
.\}
.sp
end of the output says:
.sp
.if n \{\
.RS 4
.\}
.nf
atest: 0/0 test(s) passed
atest:    1 test(s) created
.fi
.if n \{\
.RE
.\}
.sp
atest created a directory \fItest_data\fR and stored reference output into it\&.
.sp
To run a test replace \fIcTEST\fR by \fITEST\fR in \fItest/0\fR and run
.sp
.if n \{\
.RS 4
.\}
.nf
$ atest test/0
.fi
.if n \{\
.RE
.\}
.sp
It returns
.sp
.if n \{\
.RS 4
.\}
.nf
atest: RUNNING: 0
atest: PASSED : 0
atest: 1/1 test(s) passed
.fi
.if n \{\
.RE
.\}
.sp
Now if you "break" \fI\&./example\fR and run
.sp
.if n \{\
.RS 4
.\}
.nf
atest test/0
.fi
.if n \{\
.RE
.\}
.sp
it get noticed\&.
.sp
.if n \{\
.RS 4
.\}
.nf
atest: 0/1 test(s) passed
atest: failed tests:
atest:     0
.fi
.if n \{\
.RE
.\}
.SH "DESCRIPTION"
.sp
A test consists of a header line and lines which are executed as a shell script\&. Empty line ends a script\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# TEST: name
<script>
<scirpt>
<script>

<not a script>
.fi
.if n \{\
.RE
.\}
.sp
cTEST means "create" mode\&. In this mode the script updates the referense file\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# cTEST: name
.fi
.if n \{\
.RE
.\}
.sp
nTEST is "numerical" comparison mode\&. In this mode every number in the output is compared with the reference up to a tolerance 0\&.1\&. For a reference output \fB1 2 3\fR\&. A program which outputs \fB1\&.01 2 3\fR passes a test and one which outputs \fB1\&.11 2 3\fR does not\&.
.SH "EXAMPLES"
.PP
``atest atest\&.examples\&.sh``
.RS 4
Run tests in
\fIatest\&.examples\&.sh\fR
.RE
.SH "RESOURCES"
.sp
git@gitlab\&.ethz\&.ch:mavt\-cse/atest
